Fix missing attributes for img
Fix finding by https://validator.w3.org/nu/about.html
Error: Element img is missing required attribute src.
Error: An img element must have an alt attribute, except under certain conditions.